// ---------------------------------------------------------------------------
// export-glyphs.mjs — build assets/glyphs/glyphs.bin, THE glyph dictionary
// (every fontgen set in one binary file), from the committed .npz rasters
// (assets/fonts/, zero corpus pixels). Layout: tools/glyph-bundle.mjs.
// Zero dependencies (own zip/npy parser).
//
//   node tools/export-glyphs.mjs            # (re)build glyphs.bin
//   node tools/export-glyphs.mjs --check    # rebuild in memory and byte-
//         compare against the committed bundle — proves it is a pure
//         derivation of the committed rasters (npm run glyphs-check)
//
// SETS below is the explicit name → npz manifest (a new font = new line).
// Both y-phases are exported (integer and half-px baselines); rasters are
// the raw uint8 MuPDF gray windows plus the true rasterizer alpha derived
// through the set's compositor law (see COV), with (dx, dy) offsets
// relative to the integer pen / baseline and the exact dyadic freetype
// advance. The per-set JSON era (glyphs_*.json) ended 2026-07-16; the one
// parked _OFF experiment keeps its JSON as provenance.
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSetFromNpz } from './glyph-bundle.mjs';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS = join(REPO, 'assets', 'fonts');
const BUNDLE = join(REPO, 'assets', 'glyphs', 'glyphs.bin');

// name → npz manifest (bundle order; names are what --glyphs / loadSets use)
const SETS = [
  ['arial16', 'arial_16.npz'],
  ['arialbd16', 'arialbd_16.npz'],
  // NEW/calibri block (ocr/FINDINGS-calibri.md, 0 □ 2026-07-19): harvested
  // Calibri 1.02 mid-law sets + gray-23 body runs + partition-cut page-byte
  // sets for the Segoe letterhead lines and the Word/Courier bullets
  ['bullet16', 'bullet16.npz'],
  ['bullet16b', 'bullet16b.npz'],
  ['bulleto16', 'bulleto16.npz'],
  ['calibri102g23_1024', 'calibri102g23_1024.npz'],
  ['calibri102mid_1024', 'calibri102mid_1024.npz'],
  ['calibri102mid_938', 'calibri102mid_938.npz'],
  ['calibrib102mid_1024', 'calibrib102mid_1024.npz'],
  ['calibrib102mid_1194', 'calibrib102mid_1194.npz'],
  ['calibri16', 'calibri_16.npz'],
  ['calibrib16', 'calibrib_16.npz'],
  ['calibrii16', 'calibrii_16.npz'],
  ['fedline_page', 'fedline_page.npz'],
  ['ftrfouo_page', 'ftrfouo_page.npz'],
  ['hdrles_page', 'hdrles_page.npz'],
  ['cour10', 'cour_10.npz'],
  ['cour11', 'cour_11.npz'],
  ['cour12', 'cour_12.npz'],
  ['cour13', 'cour_13.npz'],
  ['cour16', 'cour_16.npz'],
  ['courbd13', 'courbd_13.npz'],
  ['courbd16', 'courbd_16.npz'],
  ['georgia16', 'georgia_16.npz'],
  ['nimbus791', 'nimbus_791.npz'],   // URW Nimbus Mono (mupdf builtin Courier CFF) em64 791 = 12.359375 px — the Outside In 7516xx block (ocr/FINDINGS.md); phy 0 only, generated by tools/fontgen.mjs
  // EFTA00039208 family (ocr/FINDINGS-nimbusrom.md): mupdf-builtin URW faces +
  // eDiscovery linear law [128,254] + per-page /Indexed palette (read with
  // blind-read --palette); ¼-px x pens, integer y (phy 0 only)
  ['nimbusromlin1024', 'nimbusromlin_1024.npz'],     // Nimbus Roman em64 1024 = 16 px — body text
  ['nimbusrombdlin1024', 'nimbusrombdlin_1024.npz'], // bold body/letterhead
  ['nimbusromlin983', 'nimbusromlin_983.npz'],       // header block (OPI/NUMBER/DATE), em64 983
  ['nimbusromilin1024', 'nimbusromilin_1024.npz'],   // italic companion
  ['nimbusrombdlin1194', 'nimbusrombdlin_1194.npz'], // "PROGRAM STATEMENT" spaced caps
  ['nimbussansbdlin1536', 'nimbussansbdlin_1536.npz'], // Nimbus Sans Bold 18pt cover title
  ['tnrlin1024', 'tnrlin_1024.npz'],                 // REAL Times New Roman (embedded subset): ■ bullets + curly quotes
  // court/ECF sub-family of the palette container (post: null, no linear) —
  // FINDINGS-nimbusrom.md §sub-family 2; body EXACT, bold/italic companions
  ['censcbk1198', 'censcbk_1198.npz'],               // Century Schoolbook 1198 — brief body
  ['censcbkbd1198', 'censcbkbd_1198.npz'],
  ['censcbki1198', 'censcbki_1198.npz'],
  ['censcbkg27_1198', 'censcbkg27_1198.npz'],        // gray srcover C=27 blockquotes (read at tol 2 — ±1 quirk)
  ['censcbkig27_1198', 'censcbkig27_1198.npz'],      // gray italic companion (case names inside blockquotes)
  ['nimbussansg118_1024', 'nimbussansg118_1024.npz'], // ECF banner gray 118 (tol 2)
  ['segoeui16', 'segoeui_16.npz'],
  ['segoeuib16', 'segoeuib_16.npz'],
  ['segoeuii16', 'segoeuii_16.npz'],
  ['times13', 'times_13.npz'],
  ['times16', 'times_16.npz'],
  ['timesbd16', 'timesbd_16.npz'],
  ['timesbd17', 'timesbd_17.npz'],
  ['timesbd18', 'timesbd_18.npz'],
  ['timesbdlin16', 'timesbdlin_16.npz'],
  ['timesi16', 'timesi_16.npz'],
  ['timesilin16', 'timesilin_16.npz'],
  ['timeslin16', 'timeslin_16.npz'],
  ['tnr8_16', 'tnr8_16.npz'],
  ['tnr8lin10', 'tnr8lin_10.667.npz'],
  ['tnr8lin16', 'tnr8lin_16.npz'],
  ['verdana16', 'verdana_16.npz'],
  ['verdanab16', 'verdanab_16.npz'],
];

// zip/npy parsing, the alpha law, and payload building are SHARED with the
// readers' direct-.npz loading path — one implementation, glyph-bundle.mjs.
const buildSet = npzBase => buildSetFromNpz(join(FONTS, npzBase));

function buildBundle() {
  const built = SETS.map(([name, npz]) => ({ name, npz, ...buildSet(npz) }));
  let dirLen = 8;
  for (const s of built) dirLen += 1 + Buffer.byteLength(s.name) + 1 + Buffer.byteLength(s.npz) + 1 + 8 + 8;
  const dir = [Buffer.from('GBF1')];
  const cnt = Buffer.alloc(4);
  cnt.writeUInt32LE(built.length, 0);
  dir.push(cnt);
  let off = dirLen;
  for (const s of built) {
    const nameB = Buffer.from(s.name), npzB = Buffer.from(s.npz);
    const e = Buffer.alloc(1 + nameB.length + 1 + npzB.length + 1 + 8 + 8);
    let p = 0;
    e.writeUInt8(nameB.length, p); nameB.copy(e, p + 1); p += 1 + nameB.length;
    e.writeUInt8(npzB.length, p); npzB.copy(e, p + 1); p += 1 + npzB.length;
    e.writeUInt8(s.linear ? 1 : 0, p); p += 1;
    e.writeDoubleLE(s.sizePx, p); p += 8;
    e.writeUInt32LE(off, p); e.writeUInt32LE(s.payload.length, p + 4);
    dir.push(e);
    off += s.payload.length;
  }
  return Buffer.concat([...dir, ...built.map(s => s.payload)]);
}

const argv = process.argv.slice(2);
const want = buildBundle();
if (argv[0] === '--check') {
  let have = null;
  try { have = readFileSync(BUNDLE); } catch {}
  if (have && have.equals(want)) {
    console.log(`ok    glyphs.bin ⇔ ${SETS.length} npz sets (${Math.round(want.length / 1024)} KB)`);
  } else {
    console.log(have ? `FAIL  glyphs.bin differs from npz rebuild (${have.length} vs ${want.length} bytes)`
      : 'FAIL  glyphs.bin missing — run: node tools/export-glyphs.mjs');
    process.exit(1);
  }
} else if (argv.length === 0) {
  writeFileSync(BUNDLE, want);
  console.log(`${BUNDLE}: ${SETS.length} sets, ${Math.round(want.length / 1024)} KB`);
} else {
  console.error('usage: node tools/export-glyphs.mjs [--check]');
  process.exit(1);
}
