// ---------------------------------------------------------------------------
// export-glyphs.mjs — build assets/glyphs/glyphs.bin, THE glyph dictionary
// (every fontgen set in one binary file), from the committed .npz rasters
// (assets/fonts/, zero corpus pixels). Layout: tools/glyph-bundle.mjs.
// Zero dependencies (own zip/npy parser).
//
//   node tools/export-glyphs.mjs            # (re)build glyphs.bin
//   node tools/export-glyphs.mjs --check    # rebuild in memory and byte-
//         compare against the committed bundle — proves it is a pure
//         derivation of the committed rasters (npm run glyphs-check)
//
// SETS below is the explicit name → npz manifest (a new font = new line).
// Both y-phases are exported (integer and half-px baselines); rasters are
// the raw uint8 MuPDF gray windows plus the true rasterizer alpha derived
// through the set's compositor law (see COV), with (dx, dy) offsets
// relative to the integer pen / baseline and the exact dyadic freetype
// advance. The per-set JSON era (glyphs_*.json) ended 2026-07-16; the one
// parked _OFF experiment keeps its JSON as provenance.
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSetFromNpz } from './glyph-bundle.mjs';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS = join(REPO, 'assets', 'fonts');
const BUNDLE = join(REPO, 'assets', 'glyphs', 'glyphs.bin');

// name → npz manifest (bundle order; names are what --glyphs / loadSets use)
const SETS = [
  ['arial16', 'arial_16.npz'],
  ['arialbd16', 'arialbd_16.npz'],
  ['calibri16', 'calibri_16.npz'],
  ['calibrib16', 'calibrib_16.npz'],
  ['calibrii16', 'calibrii_16.npz'],
  ['cour10', 'cour_10.npz'],
  ['cour11', 'cour_11.npz'],
  ['cour12', 'cour_12.npz'],
  ['cour13', 'cour_13.npz'],
  ['cour16', 'cour_16.npz'],
  ['courbd13', 'courbd_13.npz'],
  ['courbd16', 'courbd_16.npz'],
  ['georgia16', 'georgia_16.npz'],
  ['nimbus791', 'nimbus_791.npz'],   // URW Nimbus Mono (mupdf builtin Courier CFF) em64 791 = 12.359375 px — the Outside In 7516xx block (ocr/FINDINGS.md); phy 0 only, generated by tools/fontgen.mjs
  ['segoeui16', 'segoeui_16.npz'],
  ['segoeuib16', 'segoeuib_16.npz'],
  ['segoeuii16', 'segoeuii_16.npz'],
  ['times13', 'times_13.npz'],
  ['times16', 'times_16.npz'],
  ['timesbd16', 'timesbd_16.npz'],
  ['timesbd17', 'timesbd_17.npz'],
  ['timesbd18', 'timesbd_18.npz'],
  ['timesbdlin16', 'timesbdlin_16.npz'],
  ['timesi16', 'timesi_16.npz'],
  ['timesilin16', 'timesilin_16.npz'],
  ['timeslin16', 'timeslin_16.npz'],
  ['tnr8_16', 'tnr8_16.npz'],
  ['tnr8lin10', 'tnr8lin_10.667.npz'],
  ['tnr8lin16', 'tnr8lin_16.npz'],
  ['verdana16', 'verdana_16.npz'],
  ['verdanab16', 'verdanab_16.npz'],
];

// zip/npy parsing, the alpha law, and payload building are SHARED with the
// readers' direct-.npz loading path — one implementation, glyph-bundle.mjs.
const buildSet = npzBase => buildSetFromNpz(join(FONTS, npzBase));

function buildBundle() {
  const built = SETS.map(([name, npz]) => ({ name, npz, ...buildSet(npz) }));
  let dirLen = 8;
  for (const s of built) dirLen += 1 + Buffer.byteLength(s.name) + 1 + Buffer.byteLength(s.npz) + 1 + 8 + 8;
  const dir = [Buffer.from('GBF1')];
  const cnt = Buffer.alloc(4);
  cnt.writeUInt32LE(built.length, 0);
  dir.push(cnt);
  let off = dirLen;
  for (const s of built) {
    const nameB = Buffer.from(s.name), npzB = Buffer.from(s.npz);
    const e = Buffer.alloc(1 + nameB.length + 1 + npzB.length + 1 + 8 + 8);
    let p = 0;
    e.writeUInt8(nameB.length, p); nameB.copy(e, p + 1); p += 1 + nameB.length;
    e.writeUInt8(npzB.length, p); npzB.copy(e, p + 1); p += 1 + npzB.length;
    e.writeUInt8(s.linear ? 1 : 0, p); p += 1;
    e.writeDoubleLE(s.sizePx, p); p += 8;
    e.writeUInt32LE(off, p); e.writeUInt32LE(s.payload.length, p + 4);
    dir.push(e);
    off += s.payload.length;
  }
  return Buffer.concat([...dir, ...built.map(s => s.payload)]);
}

const argv = process.argv.slice(2);
const want = buildBundle();
if (argv[0] === '--check') {
  let have = null;
  try { have = readFileSync(BUNDLE); } catch {}
  if (have && have.equals(want)) {
    console.log(`ok    glyphs.bin ⇔ ${SETS.length} npz sets (${Math.round(want.length / 1024)} KB)`);
  } else {
    console.log(have ? `FAIL  glyphs.bin differs from npz rebuild (${have.length} vs ${want.length} bytes)`
      : 'FAIL  glyphs.bin missing — run: node tools/export-glyphs.mjs');
    process.exit(1);
  }
} else if (argv.length === 0) {
  writeFileSync(BUNDLE, want);
  console.log(`${BUNDLE}: ${SETS.length} sets, ${Math.round(want.length / 1024)} KB`);
} else {
  console.error('usage: node tools/export-glyphs.mjs [--check]');
  process.exit(1);
}
